server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy=ant_path_matcher: ant_path_matcher

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      jadira.usertype.autoRegisterUserTypes: true
      jadira.usertype.databaseZone: UTC
      jadira.usertype.javaZone: UTC

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mettle
    username: mettle
    password: 285051

  logging:
    level: DEBUG

  flyway:
    baseline-on-migrate: true


