server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy=ant_path_matcher: ant_path_matcher

  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      jadira.usertype.autoRegisterUserTypes: true
      jadira.usertype.databaseZone: UTC
      jadira.usertype.javaZone: UTC

  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver

  logging:
    level: DEBUG

  flyway:
    baseline-on-migrate: true


